import { requireAuthenticatedUser } from "./authUser";
import { APP_VERSION, BCID_ENGINE_VERSION } from "../config/version";
export type AnalysisType = "bcid_forecast" | "concordance" | "image_concordance" | "ast_detective" | "manual_ast";
export interface AnalysisInput { analysisType: AnalysisType; title: string; organismIds: string[]; markerIds: string[]; inputData: unknown; resultData: unknown; engineVersion: string }
export async function saveAnalysis(input: AnalysisInput) { const { client, user } = await requireAuthenticatedUser(); const { data, error } = await client.from("analyses").insert({ user_id: user.id, analysis_type: input.analysisType, title: input.title, organism_ids: input.organismIds, marker_ids: input.markerIds, input_data: input.inputData, result_data: input.resultData, app_version: APP_VERSION, engine_version: input.engineVersion }).select().single(); if (error) throw new Error("Analysis could not be saved."); return data; }
export async function getMyAnalyses() { const { client } = await requireAuthenticatedUser(); const { data, error } = await client.from("analyses").select("id,analysis_type,title,organism_ids,marker_ids,app_version,engine_version,created_at,updated_at").order("created_at", { ascending: false }); if (error) throw new Error("History could not be loaded."); return (data || []) as unknown[]; }
export async function getAnalysisById(id: string) { const { client } = await requireAuthenticatedUser(); const { data, error } = await client.from("analyses").select().eq("id", id).single(); if (error) throw new Error("Analysis could not be opened."); return data; }
export async function renameAnalysis(id: string, title: string) { const { client } = await requireAuthenticatedUser(); const { data, error } = await client.from("analyses").update({ title, updated_at: new Date().toISOString() }).eq("id", id).select().single(); if (error) throw new Error("Analysis could not be renamed."); return data; }
export async function deleteAnalysis(id: string) { const { client } = await requireAuthenticatedUser(); const { error } = await client.from("analyses").delete().eq("id", id); if (error) throw new Error("Analysis could not be deleted."); }
export const saveBcidForecast = (input: Omit<AnalysisInput, "analysisType" | "engineVersion">) => saveAnalysis({ ...input, analysisType: "bcid_forecast", engineVersion: BCID_ENGINE_VERSION });
