import { PHI_SCREENING_VERSION, type PhiScreeningResult } from "../features/phi-screening-core.mjs";
import { requireAuthenticatedUser } from "./authUser";
import { IMAGE_CONCORDANCE_ENGINE_VERSION } from "../config/version";
const bucket = "ast-images";
const extensionFor = (type: string) => type === "image/png" ? "png" : type === "image/webp" ? "webp" : "jpg";
export async function saveImageAnalysis(_file: File, phi: PhiScreeningResult, _analysis: { organismIds: string[]; markerIds: string[]; extractedResults: unknown; correctedResults: unknown; concordanceResults: unknown }) { if (phi.status !== "clear") throw new Error("Only privacy-screened images can be considered for saving."); throw new Error(`Permanent image saving is unavailable until the server PHI gate is deployed (${IMAGE_CONCORDANCE_ENGINE_VERSION}).`); }
export async function getMyImages() { const { client } = await requireAuthenticatedUser(); const { data, error } = await client.from("ast_image_uploads").select("id,original_filename,mime_type,file_size,phi_screening_version,phi_screened_at,created_at").order("created_at", { ascending: false }); if (error) throw new Error("Saved images could not be loaded."); return (data || []) as unknown[]; }
export async function getSignedImageUrl(storagePath: string) { const { client, user } = await requireAuthenticatedUser(); if (!storagePath.startsWith(`${user.id}/`)) throw new Error("Image access denied."); const { data, error } = await client.storage.from(bucket).createSignedUrl(storagePath, 300); if (error || !data) throw new Error("Temporary image access could not be created."); return data.signedUrl; }
export async function deleteImage(id: string, storagePath: string) { const { client, user } = await requireAuthenticatedUser(); if (!storagePath.startsWith(`${user.id}/`)) throw new Error("Image access denied."); const removed = await client.storage.from(bucket).remove([storagePath]); if (removed.error) throw new Error("Image could not be deleted."); const { error } = await client.from("ast_image_uploads").delete().eq("id", id); if (error) throw new Error("Image metadata could not be deleted."); }
