import { useMemo, useState } from "react";
import { assessBcidPairs, bcid2Panel, bcidForecasts, getCombinedForecast, getCompatibilityRule, getMarkersForOrganism, getOrganismsForMarker, isCompatibleBcidPair, mechanisms, references, type BcidPanelTarget, type BcidResistanceMarker, type ForecastPrediction } from "../data";
import SearchableSelect from "../components/SearchableSelect";
import { sortAlphabetically, type SearchOption } from "../utils/search";
import { useAuth } from "../auth/AuthContext";
import { saveBcidForecast } from "../services/analysisService";

const predictionOrder: ForecastPrediction[] = ["Resistance strongly expected", "Activity may be retained", "Mechanism-dependent caution", "Cannot infer"];
const predictionTone: Record<ForecastPrediction, string> = { "Resistance strongly expected": "resistance", "Activity may be retained": "retained", "Cannot infer": "unknown", "Mechanism-dependent caution": "caution" };
const categoryOrder = ["Gram-negative bacteria", "Gram-positive bacteria", "Yeast"] as const;
const markerOrder: BcidResistanceMarker["category"][] = ["ESBL", "Carbapenemase", "Colistin resistance", "Methicillin resistance", "Vancomycin resistance"];
const targetById = (id: string) => bcid2Panel.targets.find((target) => target.id === id);
const markerById = (id: string) => bcid2Panel.markers.find((marker) => marker.id === id);
const optionForTarget = (target: BcidPanelTarget): SearchOption => ({ value: target.id, label: target.name, aliases: target.aliases, group: target.category, description: target.parentId ? "Within " + targetById(target.parentId)?.name : target.targetType });
const optionForMarker = (marker: BcidResistanceMarker, context?: string, conditional = false): SearchOption => ({ value: marker.id, label: marker.label, group: marker.category, description: conditional ? `CONDITIONAL · ${context || "attribution caution"}` : context || marker.mechanismFamily || mechanisms.find((item) => item.id === marker.mechanismId)?.name });

function forecastsFor(target: BcidPanelTarget, marker: BcidResistanceMarker) {
  const exact = bcidForecasts.filter((row) => row.organism === target.name && row.markerLabel === marker.label);
  if (exact.length) return exact;
  const group = bcidForecasts.filter((row) => row.organismGroup === target.name && row.markerLabel === marker.label);
  if (group.length) return group;
  const parent = target.parentId ? targetById(target.parentId) : undefined;
  return bcidForecasts.filter((row) => row.organismGroup === parent?.name && row.markerLabel === marker.label);
}

export default function BcidForecast() {
  const auth = useAuth();
  const [startWith, setStartWith] = useState<"organism" | "marker">("organism");
  const [organismIds, setOrganismIds] = useState<string[]>(["e-coli"]);
  const [markerMode, setMarkerMode] = useState<"none" | "detected">("none");
  const [markerIds, setMarkerIds] = useState<string[]>([]);
  const [showAdvanced, setShowAdvanced] = useState(false);
  const [saveStatus, setSaveStatus] = useState("");
  const organisms = organismIds.map(targetById).filter((item): item is BcidPanelTarget => !!item);
  const markers = markerIds.map(markerById).filter((item): item is BcidResistanceMarker => !!item);
  const relevantMarkerIds = [...new Set(organismIds.flatMap((id) => getMarkersForOrganism(id, showAdvanced)))];
  const relevantOrganismIds = markerIds.length ? [...new Set(markerIds.flatMap((id) => getOrganismsForMarker(id, showAdvanced)))] : bcid2Panel.targets.map((item) => item.id);
  const organismOptions = (startWith === "marker" && markerIds.length ? bcid2Panel.targets.filter((item) => relevantOrganismIds.includes(item.id)) : bcid2Panel.targets).map(optionForTarget);
  const markerOptions = relevantMarkerIds.map(markerById).filter((item): item is BcidResistanceMarker => !!item).map((item) => {
    const relevant = organisms.filter((organism) => isCompatibleBcidPair(organism.id, item.id, showAdvanced)).map((organism) => organism.name).join(", ");
    return optionForMarker(item, `Relevant to: ${relevant}`, organisms.some((organism) => getCompatibilityRule(organism.id, item.id)?.compatibility === "possible"));
  });
  const pairAssessments = useMemo(() => assessBcidPairs(organismIds, markerIds), [organismIds, markerIds]);
  const multiplex = organismIds.length > 1 || markerIds.length > 1;
  const changeOrganisms = (ids: string[]) => { setOrganismIds(ids); const allowed = new Set(ids.flatMap((id) => getMarkersForOrganism(id, showAdvanced))); setMarkerIds((current) => current.filter((id) => allowed.has(id))); };
  const changeMarkers = (ids: string[]) => { setMarkerIds(ids); if (ids.length) setMarkerMode("detected"); if (startWith === "marker" && ids.length) { const allowed = new Set(ids.flatMap((id) => getOrganismsForMarker(id, showAdvanced))); setOrganismIds((current) => current.filter((id) => allowed.has(id))); } };

  return <>
    <div className="bcid-page-head"><div><p className="eyebrow">Rapid blood-culture result review</p><h1>BCID Forecast</h1><p>Model a multiplex organism and AMR-marker result, review possible relationships, and frame pre-AST expectations.</p></div><div className="bcid-metadata"><b>BCID PANEL</b><strong>43 targets</strong><span>26 bacteria · 7 yeast · 10 AMR targets</span><small>Panel menu verified September 1, 2026</small></div></div>
    <div className="preast-banner"><b>PRE-AST EXPECTATION ONLY</b><span>A detected molecular marker is not equivalent to a phenotypic susceptibility result. AST Compass is a compass, not an autopilot.</span></div>
    {multiplex && <div className="attribution-warning multiplex-top"><b>MULTIPLEX ATTRIBUTION CAUTION</b><p>Multiple organisms and/or resistance markers were detected. Do not assume that every marker belongs to every detected organism.</p><span>Review compatibility and confirm the final phenotype using culture, additional testing, validated AST, and laboratory policy.</span></div>}
    <div className="bcid-workflow"><aside className="panel bcid-input">
      <section><span className="step-number">START WITH</span><div className="workflow-start"><label><input type="radio" name="start-with" checked={startWith === "organism"} onChange={() => { setStartWith("organism"); setOrganismIds(["e-coli"]); setMarkerIds([]); }}/> Organism(s)</label><label><input type="radio" name="start-with" checked={startWith === "marker"} onChange={() => { setStartWith("marker"); setMarkerMode("detected"); setOrganismIds([]); setMarkerIds([]); }}/> Marker(s)</label></div></section>
      {startWith === "marker" && <section><span className="step-number">STEP 1</span><h2>Resistance marker(s)</h2><MultiSelect label="Detected resistance marker(s)" values={markerIds} onChange={changeMarkers} options={bcid2Panel.markers.map((item) => optionForMarker(item))} placeholder="Search another marker…"/></section>}
      <section><span className="step-number">{startWith === "organism" ? "STEP 1" : "STEP 2"}</span><h2>Detected organism(s)</h2><MultiSelect label="Detected organism(s)" values={organismIds} onChange={changeOrganisms} options={organismOptions} placeholder="Search another organism…"/><p className="filter-note">{startWith === "marker" && markerIds.length ? "Showing organism contexts relevant to any selected marker." : "Select every organism reported in the multiplex result."}</p></section>
      {startWith === "organism" && <section><span className="step-number">STEP 2</span><h2>Detected AMR marker(s)</h2><div className="marker-mode"><label><input type="radio" name="marker-mode" checked={markerMode === "none"} onChange={() => { setMarkerMode("none"); setMarkerIds([]); }}/> No resistance marker detected</label><label><input type="radio" name="marker-mode" checked={markerMode === "detected"} onChange={() => setMarkerMode("detected")}/> One or more markers detected</label></div>{markerMode === "detected" && (relevantMarkerIds.length ? <><MultiSelect label="Detected resistance marker(s)" values={markerIds} onChange={changeMarkers} options={markerOptions} placeholder="Search another relevant marker…"/><p className="filter-note">Showing the union of BCID markers relevant to all selected organisms.</p></> : <NoRelevantMarker compact/>)}<label className="advanced-toggle"><input type="checkbox" checked={showAdvanced} onChange={(event) => { setShowAdvanced(event.target.checked); const allowed = new Set(organismIds.flatMap((id) => getMarkersForOrganism(id, event.target.checked))); setMarkerIds((current) => current.filter((id) => allowed.has(id))); }}/> Show advanced/conditional marker associations</label><details className="why-filter"><summary>Why don't I see other genes?</summary><p>Markers unrelated to every selected organism are hidden. This prevents biologically irrelevant pairings from appearing meaningful.</p></details></section>}
      <div className="forecast-chain"><span>Detected organism(s)</span><i>+</i><span>Detected AMR marker(s)</span><i>↓</i><span>Compatibility matrix</span><i>↓</i><span>Possible relationships</span><i>↓</i><span>Mechanism forecasts</span><i>↓</i><span>Phenotypic AST confirmation</span></div>
    </aside><section className="panel forecast-panel"><ResultCard organisms={organisms} markers={markers} markerMode={markerMode}/>{markerMode === "none" ? <NoMarkerMessage/> : !organisms.length || !markers.length ? <SelectResultMessage/> : <><PairMatrix organisms={organisms} markers={markers} assessments={pairAssessments}/>{multiplex && <PossibleRelationships organisms={organisms} markers={markers}/>}<MechanismForecasts organisms={organisms} markers={markers}/><div className="save-work"><button className="primary" type="button" onClick={() => { if (!auth.user) { sessionStorage.setItem("ast-guest-bcid", JSON.stringify({ organismIds, markerIds })); setSaveStatus("Sign in or create an account to save this analysis. Your current selections remain in this guest session."); return; } void saveBcidForecast({ title: `${organisms.map((item) => item.name).join(" + ")} · ${markers.map((item) => item.label).join(" + ")}`, organismIds, markerIds, inputData: { organismIds, markerIds }, resultData: { pairAssessments, multiplex } }).then(() => setSaveStatus("Saved to My AST Compass ✓")).catch(() => setSaveStatus("This analysis could not be saved.")); }}>Save to My AST Compass</button>{saveStatus && <p aria-live="polite">{saveStatus}</p>}</div></>}</section></div>
    <PanelBrowser/><div className="bcid-manufacturer-note"><b>Independent educational resource</b><p>Panel target information is based on publicly available manufacturer documentation. See the retained source references for panel details and limitations.</p><div>{bcid2Panel.metadata.sourceIds.map((id) => { const reference = references.find((item) => item.id === id); return reference ? <a href={reference.url} target="_blank" rel="noreferrer" key={id}>{reference.short} ↗</a> : null; })}</div></div>
  </>;
}

function MultiSelect({ label, values, onChange, options, placeholder }: { label: string; values: string[]; onChange: (values: string[]) => void; options: SearchOption[]; placeholder: string }) { const [candidate, setCandidate] = useState(""); const selected = values.map((value) => options.find((option) => option.value === value) || (targetById(value) ? optionForTarget(targetById(value)!) : markerById(value) ? optionForMarker(markerById(value)!) : undefined)).filter((item): item is SearchOption => !!item); return <div className="multi-select"><span className="multi-label">{label}</span>{selected.length > 0 && <div className="detected-chips">{selected.map((option) => <span key={option.value}>{option.label}<button type="button" aria-label={`Remove ${option.label}`} onClick={() => onChange(values.filter((value) => value !== option.value))}>×</button></span>)}</div>}<SearchableSelect label={`Add ${label}`} value={candidate} onChange={(value) => { if (value) { onChange([...values, value]); setCandidate(""); } }} options={options.filter((option) => !values.includes(option.value))} placeholder={placeholder}/></div>; }

function ResultCard({ organisms, markers, markerMode }: { organisms: BcidPanelTarget[]; markers: BcidResistanceMarker[]; markerMode: "none" | "detected" }) { return <div className="bcid-result-card"><span>BCID RESULT</span><dl><div><dt>Organisms detected</dt><dd>{organisms.length ? <ul>{organisms.map((item) => <li key={item.id}>{item.name}</li>)}</ul> : "Select organism(s)"}</dd></div><div><dt>AMR markers detected</dt><dd>{markerMode === "none" ? "No BCID marker detected" : markers.length ? <ul>{markers.map((item) => <li key={item.id}>{item.label}</li>)}</ul> : "Select marker(s)"}</dd></div><div><dt>Interpretation stage</dt><dd>Pre-AST molecular result</dd></div></dl></div>; }
function PairMatrix({ organisms, markers, assessments }: { organisms: BcidPanelTarget[]; markers: BcidResistanceMarker[]; assessments: ReturnType<typeof assessBcidPairs> }) { return <section className="pair-matrix"><p className="eyebrow">ORGANISM–MARKER RELATIONSHIPS</p><h2>Attribution matrix</h2><div className="matrix-scroll"><table><thead><tr><th>Detected organism</th>{markers.map((marker) => <th key={marker.id}>{marker.label}</th>)}</tr></thead><tbody>{organisms.map((organism) => <tr key={organism.id}><th>{organism.name}</th>{markers.map((marker) => { const item = assessments.find((row) => row.organismId === organism.id && row.markerId === marker.id)!; const label = item.compatibility === "not-applicable" ? "Not applicable" : item.compatibility === "possible" ? "Possible" : item.attribution === "ambiguous" ? "Primary · uncertain attribution" : "Primary"; return <td key={marker.id} className={item.compatibility}>{label}</td>; })}</tr>)}</tbody></table></div></section>; }
function PossibleRelationships({ organisms, markers }: { organisms: BcidPanelTarget[]; markers: BcidResistanceMarker[] }) { return <section className="possible-relationships"><h2>Possible organism–marker relationships</h2>{markers.map((marker) => { const compatible = organisms.filter((organism) => isCompatibleBcidPair(organism.id, marker.id)); return <article key={marker.id}><h3>{marker.label}</h3>{compatible.length ? <><ul>{compatible.map((organism) => <li key={organism.id}>{organism.name} — {getCompatibilityRule(organism.id, marker.id)?.compatibility === "possible" ? "possible / conditional" : "compatible"}</li>)}</ul><p>{compatible.length === 1 ? `Among the selected organisms, ${marker.label} is relevant to the ${compatible[0].name} context.` : `${marker.label} is compatible with more than one detected organism. Attribution remains uncertain.`}</p></> : <p>No applicable selected organism context.</p>}</article>; })}<div className="attribution-warning"><b>GENE-TO-ORGANISM ATTRIBUTION CAUTION</b><p>The multiplex result may not establish which resistance marker belongs to which organism.</p></div></section>; }
function MechanismForecasts({ organisms, markers }: { organisms: BcidPanelTarget[]; markers: BcidResistanceMarker[] }) { return <section className="mechanism-forecasts"><p className="eyebrow">DETECTED MECHANISMS</p>{markers.map((marker) => <article className="mechanism-chip" key={marker.id}><b>{marker.label}</b><span>{mechanisms.find((item) => item.id === marker.mechanismId)?.name || marker.category}</span></article>)}{organisms.map((organism) => { const compatible = markers.filter((marker) => isCompatibleBcidPair(organism.id, marker.id)); if (!compatible.length) return null; const combined = compatible.length > 1 ? getCombinedForecast(organism.id, compatible.map((item) => item.id)) : undefined; return <section className="organism-forecast" key={organism.id}><h2>{organism.name}</h2>{combined && <div className={combined.reviewed ? "combined-forecast reviewed" : "combined-forecast unreviewed"}><span>COMBINED EXPECTED PHENOTYPE</span><h3>{combined.title}</h3><p>{combined.interpretation}</p>{!combined.reviewed && <b>No reviewed combined rule — individual expectations follow.</b>}</div>}{compatible.map((marker) => <IndividualForecast key={marker.id} organism={organism} marker={marker}/>)}</section>; })}<section className="forecast-limit"><h3>AST confirmation</h3><p>The complete phenotype cannot be established from molecular markers alone. Confirm organism identity, attribution, and antimicrobial susceptibility using culture, validated phenotypic AST, and laboratory policy.</p></section></section>; }
function IndividualForecast({ organism, marker }: { organism: BcidPanelTarget; marker: BcidResistanceMarker }) { const rows = forecastsFor(organism, marker); const classes = sortAlphabetically([...new Set(rows.map((row) => row.antimicrobialClass))], (item) => item); return <section className="individual-forecast"><h3>{marker.label} · {organism.name}</h3>{rows.length ? classes.map((className) => <section className="forecast-class" key={className}><h4>{className}</h4><div className="forecast-groups">{predictionOrder.map((prediction) => { const group = rows.filter((row) => row.antimicrobialClass === className && row.prediction === prediction); return group.length ? <section className={`forecast-group ${predictionTone[prediction]}`} key={prediction}><h4>{prediction}</h4>{group.map((row) => <article key={row.id}><div><b>{row.drugOrClass}</b><span>{row.confidence} confidence</span></div><p>{row.rationale}</p><small><strong>Important exception:</strong> {row.exceptions}</small></article>)}</section> : null; })}</div></section>) : <NoForecast/>}</section>; }
function NoMarkerMessage() { return <div className="no-marker-message"><span>NO BCID RESISTANCE MARKER DETECTED</span><h2>Absence of a panel marker does not establish susceptibility.</h2><p>Resistance mechanisms outside the panel may be present.</p><b>Phenotypic AST remains required.</b></div>; }
function SelectResultMessage() { return <div className="no-reviewed-forecast"><span>COMPLETE THE DETECTED RESULT</span><h2>Select at least one organism and one resistance marker.</h2><p>AST Compass will analyze the many-to-many compatibility context without forcing attribution.</p></div>; }
function NoRelevantMarker({ compact = false }: { compact?: boolean }) { return <div className={compact ? "no-relevant-marker compact" : "no-relevant-marker"}><span>NO ORGANISM-SPECIFIC BCID AMR MARKER AVAILABLE</span><p>The BCID panel identifies this organism, but AST Compass has no relevant organism-specific marker forecast. This does not imply susceptibility.</p><b>Phenotypic AST remains important.</b></div>; }
function NoForecast() { return <div className="no-reviewed-forecast"><span>NO REVIEWED FORECAST</span><h2>No reviewed forecast is available for this exact combination.</h2><p>AST Compass will not fabricate a phenotype.</p></div>; }
function PanelBrowser() { return <details className="panel-browser"><summary>View BCID Panel Menu <span>43 targets</span></summary><div className="panel-browser-grid">{categoryOrder.map((category) => <section key={category}><h2>{category}</h2><ul>{sortAlphabetically(bcid2Panel.targets.filter((target) => target.category === category && !target.parentId), (target) => target.name).map((target) => <li key={target.id}><b>{target.name}</b>{bcid2Panel.targets.some((child) => child.parentId === target.id) && <ul>{sortAlphabetically(bcid2Panel.targets.filter((child) => child.parentId === target.id), (child) => child.name).map((child) => <li key={child.id}>{child.name}</li>)}</ul>}</li>)}</ul></section>)}<section><h2>AMR markers</h2>{markerOrder.map((category) => <div key={category}><h3>{category}</h3><ul>{sortAlphabetically(bcid2Panel.markers.filter((marker) => marker.category === category), (marker) => marker.label).map((marker) => <li key={marker.id}>{marker.label}</li>)}</ul></div>)}</section></div></details>; }
