import { useMemo, useState } from "react";
import { antibiotics, breakpoints, organisms, references, standardCatalog, type Standard, type SusceptibilityDomain } from "../data";

const domains: SusceptibilityDomain[] = ["Bacteria", "Yeast", "Filamentous fungi", "Anaerobes", "Fastidious bacteria", "Rapid AST", "Mycobacteria"];
const refFor = (id: string) => references.find((r) => r.id === id);

export default function BreakpointEngine() {
  const [domain, setDomain] = useState<SusceptibilityDomain>("Bacteria");
  const [standard, setStandard] = useState<Standard>("CLSI");
  const [recordId, setRecordId] = useState(breakpoints[0].id);
  const catalog = standardCatalog.filter((s) => s.domain === domain || (domain === "Anaerobes" && s.id === "eucast-161"));
  const records = useMemo(() => domain === "Bacteria" ? breakpoints.filter((b) => b.standard === standard) : [], [domain, standard]);
  const record = records.find((b) => b.id === recordId) || records[0];
  return <>
    <div className="page-head"><p className="eyebrow">Versioned susceptibility reference architecture</p><h1>Breakpoint Engine</h1><p>Navigate standards by organism domain and method. Source versions are verified labels; all displayed breakpoint values remain unvalidated demo content.</p></div>
    <div className="domain-tabs" role="tablist">{domains.map((d) => <button role="tab" aria-selected={domain === d} className={domain === d ? "selected" : ""} onClick={() => setDomain(d)} key={d}>{d}</button>)}</div>
    <section className="catalog-strip">{catalog.length ? catalog.map((entry) => <article key={entry.id}><div><span>{entry.authority}</span><b>{entry.document}</b><small>{entry.edition}</small></div><p>{entry.purpose}</p><a href={refFor(entry.sourceId)?.url} target="_blank" rel="noreferrer">Source ↗</a><em>{entry.implementationStatus}</em></article>) : <article className="no-source"><b>Domain scaffolded</b><p>An authoritative source has not yet been selected or ingested.</p></article>}</section>
    {domain === "Rapid AST" && <div className="rapid-warning"><b>Rapid AST uses its own criteria.</b><span>EUCAST states that standard breakpoint tables must not be used for direct-from-positive-blood-culture RAST. The dedicated v9.0 dataset is planned and remains unavailable in this demo.</span></div>}
    <div className="standard-hero"><div><span>Selected interpretive context</span><b>{domain} · {standard}</b><small>{standard === "EUCAST" ? "EUCAST I = susceptible, increased exposure." : "Authorized current publication required before clinical use."}</small></div><div className="standard-buttons">{(["CLSI", "EUCAST", "FDA"] as Standard[]).map((s) => <button className={standard === s ? "selected" : ""} onClick={() => setStandard(s)} key={s}>{s}</button>)}</div></div>
    {record ? <div className="workspace-grid"><aside className="filter-panel"><label>Demo record<select value={record.id} onChange={(e) => setRecordId(e.target.value)}>{records.map((b) => <option value={b.id} key={b.id}>{organisms.find((o) => o.id === b.organismId)?.name} · {antibiotics.find((a) => a.id === b.antibioticId)?.name}</option>)}</select></label><div className="warning-box"><b>DEMO / UNVALIDATED</b><p>Values are interface fixtures, not validated current criteria.</p></div></aside><section className="panel result-panel"><div className="result-title"><div><p className="eyebrow">{organisms.find((o) => o.id === record.organismId)?.name}</p><h2>{antibiotics.find((a) => a.id === record.antibioticId)?.name}</h2><span>{record.method} · {record.unit}</span></div><span className="demo-stamp">DEMO</span></div><div className="breakpoint-scale"><div className="sus"><span>S</span><b>{record.susceptible}</b><small>Susceptible</small></div><div className="int"><span>I / SDD</span><b>{record.intermediate}</b><small>{record.standard === "EUCAST" ? "Increased exposure" : "Intermediate / SDD"}</small></div><div className="res"><span>R</span><b>{record.resistant}</b><small>Resistant</small></div></div><div className="detail-grid"><div><span>Standard / version</span><b>{record.standard} · {record.version}</b></div><div><span>Effective date</span><b>{record.effectiveDate}</b></div><div><span>Table</span><b>{record.table}</b></div><div><span>Review status</span><b>{record.meta.status}</b></div></div><div className="note"><b>Interpretive note</b><p>{record.footnote}</p></div></section></div> : <section className="no-breakpoint"><span>∅</span><div><p className="eyebrow">Explicit data state</p><h2>No validated breakpoint available in AST Compass</h2><p>This is not a susceptible or resistant result. The selected domain has no ingested, reviewed breakpoint record. Consult the linked authoritative source and laboratory policy.</p><a href={refFor("ref-eucast-nobp")?.url} target="_blank" rel="noreferrer">Read EUCAST no-breakpoint guidance ↗</a></div></section>}
  </>;
}

