import { FormEvent, useState } from "react";
import { useAuth } from "../auth/AuthContext";
import { submitFeedback } from "../services/feedbackService";
import { captureError, trackEvent } from "../lib/telemetry";

const roles = ["Medical Laboratory Scientist / Clinical Laboratory Scientist","Microbiology Technologist","Resident","Fellow","Student","Educator","Researcher","Physician","Pharmacist","Other","Prefer not to say"];
const emptyForm = { displayName:"", email:"", role:"", rating:"", useful:"", improvement:"", requestedFeature:"", comments:"", testimonialPermission:false, website:"" };

export default function Feedback({ onReturn }: { onReturn: () => void }) {
  const auth=useAuth(),[form,setForm]=useState(emptyForm),[status,setStatus]=useState<"idle"|"sending"|"success"|"error">("idle");
  const update=(key:keyof typeof form,value:string|boolean)=>setForm(current=>({...current,[key]:value}));
  const submit=async(event:FormEvent)=>{event.preventDefault();if(form.website)return;const last=Number(localStorage.getItem("ast-feedback-last")||0);if(Date.now()-last<30000){setStatus("error");return;}setStatus("sending");try{await submitFeedback({...form,rating:form.rating?Number(form.rating):null,userId:auth.user?.id||null,accountStatus:auth.user?"Authenticated":"Guest",pageSource:location.pathname});localStorage.setItem("ast-feedback-last",String(Date.now()));trackEvent("feedback_submitted",{page:"/feedback",feature_name:"feedback",guest_or_authenticated:auth.user?"authenticated":"guest",success_or_failure:"success"});setStatus("success");}catch(error){captureError(error,{feature_name:"feedback",success_or_failure:"failure"});setStatus("error");}};
  if(status==="success")return <section className="feedback-success" role="status"><span>✓</span><h1>Thank you for helping improve AST Compass.</h1><p>Your feedback has been received and will help guide future improvements to the platform.</p><button className="primary" onClick={onReturn}>Return to AST Compass</button></section>;
  return <><div className="page-head"><p className="eyebrow">Private product feedback</p><h1>Help Improve AST Compass</h1><p>AST Compass is built to support learning and practical microbiology education. Your feedback helps identify what works well, what needs improvement, and what tools would be most useful next.</p></div><form className="feedback-form panel" onSubmit={submit}><div className="phi-warning"><b>Please do not include patient information or PHI in your feedback.</b><span>Do not enter names, MRNs, accession numbers, dates of birth, or clinical case identifiers.</span></div><div className="feedback-grid"><label>Name or display name <small>Optional</small><input value={form.displayName} onChange={e=>update("displayName",e.target.value)} /></label><label>Email <small>Optional</small><input type="email" value={form.email} onChange={e=>update("email",e.target.value)} /></label><label>Role <small>Optional</small><select value={form.role} onChange={e=>update("role",e.target.value)}><option value="">Select a role</option>{roles.map(role=><option key={role}>{role}</option>)}</select></label><fieldset><legend>Overall experience <small>Optional</small></legend><div className="rating-row">{[1,2,3,4,5].map(n=><label key={n}><input type="radio" name="rating" value={n} checked={form.rating===String(n)} onChange={e=>update("rating",e.target.value)}/><span>{n}</span></label>)}</div></fieldset></div>{[["useful","What did you find useful?"],["improvement","What could be improved?"],["requestedFeature","What feature would you like to see next?"],["comments","Additional comments"]].map(([key,label])=><label className="feedback-long" key={key}>{label}<textarea rows={4} value={form[key as keyof typeof form] as string} onChange={e=>update(key as keyof typeof form,e.target.value)}/></label>)}<label className="honeypot" aria-hidden="true">Website<input tabIndex={-1} autoComplete="off" value={form.website} onChange={e=>update("website",e.target.value)}/></label><label className="testimonial"><input type="checkbox" checked={form.testimonialPermission} onChange={e=>update("testimonialPermission",e.target.checked)}/> You may contact me about using this feedback as a testimonial.</label><small>Feedback remains private. It is not published automatically.</small>{status==="error"&&<div className="form-error" role="alert">We couldn't submit your feedback right now. Please try again. Your entries are still here.</div>}<button className="primary" disabled={status==="sending"}>{status==="sending"?"Sending…":"Send private feedback →"}</button></form></>;
}

