type LegalSection = { title: string; paragraphs?: string[]; bullets?: string[] };

function LegalLayout({ kind, title, intro, sections, plainTitle, plainItems, onFeedback }: { kind: "privacy" | "terms"; title: string; intro: string; sections: LegalSection[]; plainTitle: string; plainItems: string[]; onFeedback: () => void }) {
  return <article className="legal-page">
    <header className="legal-hero"><p className="eyebrow">AST Compass trust center</p><h1>{title}</h1><p>{intro}</p><dl><div><dt>Effective Date</dt><dd>September 2, 2026</dd></div><div><dt>Last Updated</dt><dd>September 2, 2026</dd></div></dl></header>
    <aside className={`legal-alert ${kind}`}><b>{kind === "privacy" ? "DO NOT UPLOAD PHI" : "EDUCATIONAL USE ONLY"}</b><p>{kind === "privacy" ? "Do not upload protected health information or patient-identifiable information. Images must be fully de-identified before submission." : "AST Compass does not replace validated laboratory procedures, current authoritative standards, institutional policy, manufacturer instructions, or professional judgment."}</p></aside>
    <nav className="legal-toc" aria-label={`${title} contents`}><b>On this page</b><div>{sections.map((section, index) => <a href={`#legal-${kind}-${index + 1}`} key={section.title}>{section.title}</a>)}</div></nav>
    <div className="legal-content">{sections.map((section, index) => <section id={`legal-${kind}-${index + 1}`} key={section.title}><h2>{section.title}</h2>{section.paragraphs?.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.bullets && <ul>{section.bullets.map((item) => <li key={item}>{item}</li>)}</ul>}{section.title === "Contact" && <button className="secondary" onClick={onFeedback}>Open AST Compass Feedback →</button>}</section>)}</div>
    <section className="legal-plain"><p className="eyebrow">Quick summary</p><h2>{plainTitle}</h2><ul>{plainItems.map((item) => <li key={item}>{item}</li>)}</ul>{kind === "terms" && <strong>A compass, not an autopilot.</strong>}</section>
    <p className="legal-note">This page describes AST Compass's current policies and product boundaries. It is not legal advice.</p>
  </article>;
}

const privacySections: LegalSection[] = [
  { title: "About AST Compass", paragraphs: ["AST Compass respects user privacy and is designed to minimize collection of personal information while providing educational tools for antimicrobial susceptibility testing, resistance mechanisms, molecular–phenotypic concordance, and clinical microbiology learning.", "AST Compass is an independent educational and laboratory reference-support platform. It does not replace validated laboratory procedures, institutional policies, manufacturer instructions, current authoritative standards, professional judgment, or patient-specific clinical decision-making."] },
  { title: "Public Access", paragraphs: ["AST Compass currently works without an account. All public scientific and educational tools are available immediately, and activity is session-only unless a feature explicitly states otherwise. Account functionality may be introduced or enabled in the future after authentication, recovery, deletion, authorization, and private-storage controls have been validated."] },
  { title: "Potential Future Account Information", paragraphs: ["If optional account functionality is enabled in the future, AST Compass may process a display name or username, email address, authentication information, saved analyses, BCID sessions, Concordance history, learning progress, preferences, and de-identified AST images explicitly saved by the user.", "Passwords would not be stored by AST Compass in readable form. Managed authentication infrastructure would handle authentication. If a third-party authentication provider is offered and selected, that provider would also process information under its own privacy practices."] },
  { title: "Do Not Upload PHI", paragraphs: ["DO NOT UPLOAD PROTECTED HEALTH INFORMATION (PHI) OR PATIENT-IDENTIFIABLE INFORMATION TO AST COMPASS. Image tools are intended only for de-identified educational or laboratory training material.", "Before upload, remove patient names, medical record numbers, dates of birth, addresses, phone numbers, email addresses, account or member numbers, patient-linked accession or specimen identifiers, patient labels, identifying barcodes or QR codes, identifiable photographs, and any other patient-specific identifiers.", "Automated privacy screening may reject an image when an identifier is detected, suspected, or cannot be reliably excluded. Screening cannot guarantee detection of every identifier and is not legal certification of HIPAA de-identification. Users remain responsible for de-identification."] },
  { title: "Image Processing and Storage", paragraphs: ["Public image analyses are processed for the current session and are not added to a persistent personal history. Uploaded images are not permanently saved through the public Image Concordance workflow.", "If private account storage is enabled in the future, it may offer options to save a de-identified image and analysis, save the analysis only, or save neither, using validated authorization and deletion controls."] },
  { title: "Information Generated Through AST Compass", paragraphs: ["The platform may process selected organisms, antimicrobials, resistance markers, MIC values, susceptibility categories, concordance assessments, BCID forecasts, learning and AST Detective activity, timestamps, application or engine version, and corrections to extracted AST information. If optional account functionality is enabled in the future, this information may be associated with an account so a user can reopen work across sessions or devices."] },
  { title: "How Information Is Used", bullets: ["Provide requested public AST Compass functionality without requiring an account.", "If optional accounts are enabled in the future, authenticate users and save or restore user-requested work and learning progress.", "Process de-identified AST images for the current public session.", "Troubleshoot problems, maintain security, and improve reliability and usability.", "Understand how AST Compass can be improved."], paragraphs: ["Uploaded laboratory images are not used to independently make patient-specific treatment decisions."] },
  { title: "Feedback", paragraphs: ["Feedback is voluntary and may include an optional name or email, professional or learner role, rating, comments, suggestions, and requested features. Do not include PHI or patient information in Feedback.", "Feedback may be stored using services used to organize and review product feedback. Submission does not authorize AST Compass to publicly identify a user or publish an identifiable testimonial; separate permission should be obtained."] },
  { title: "Analytics and Error Monitoring", paragraphs: ["AST Compass may use privacy-conscious analytics and error-monitoring services to understand platform use, identify technical problems, measure feature performance, and improve reliability. Information may include pages or features used, general device or browser information, approximate usage timing, application version, generic error information, and non-sensitive performance information.", "AST Compass is designed not to intentionally send uploaded AST images, OCR content, MIC tables, passwords, authentication credentials, PHI, feedback text, or other sensitive laboratory content to analytics or crash-reporting services. Analytics are minimized and used only for product improvement, security, reliability, and usage understanding—not advertising, cross-site tracking, data brokerage, or behavioral ad profiles."] },
  { title: "Service Providers", paragraphs: ["AST Compass may use third-party infrastructure for hosting, authentication, database and private file storage, email verification, feedback collection, application infrastructure, and security. This policy identifies services only when actually configured and does not describe planned integrations as already operating."] },
  { title: "Security", paragraphs: ["AST Compass uses reasonable technical and organizational safeguards appropriate to the information processed. These may include HTTPS/TLS, managed authentication, protected password handling, private records and files, database authorization policies, and automated PHI screening.", "No website, database, transmission method, or security system can guarantee absolute security. Avoid submitting information AST Compass does not require."] },
  { title: "HIPAA and Clinical Information", paragraphs: ["AST Compass follows a No-PHI policy. It is not an electronic medical record, laboratory information system, patient-record repository, clinical-document archive, or storage system for identifiable patient laboratory reports.", "AST Compass does not claim that automated screening makes an image HIPAA compliant or legally de-identified. Unless explicitly stated after appropriate technical, contractual, legal, operational, and compliance review, AST Compass should not be considered a HIPAA-compliant system for storing or processing PHI."] },
  { title: "Data Retention", paragraphs: ["Personal information is retained only as reasonably necessary to provide requested functionality, meet legitimate security requirements, or comply with applicable obligations. Public image processing is session-only. If account functionality is enabled in the future, its saved material may remain until deleted, subject to disclosed backup, security, and technical retention periods."] },
  { title: "User Choices and Controls", bullets: ["Use all public AST Compass scientific and educational tools without an account.", "Submit optional Feedback without creating an account.", "If account functionality is enabled in the future, applicable controls will explain how to view or delete saved work and manage an account." ] },
  { title: "Account Deletion", paragraphs: ["If optional account functionality is enabled in the future, account deletion should remove or schedule deletion of associated user-controlled analyses and images, subject to legitimate technical, security, backup, fraud-prevention, or legal retention requirements."] },
  { title: "Children's Privacy", paragraphs: ["AST Compass is designed for professional and educational microbiology use and is not specifically directed toward young children. It does not knowingly seek personal information from children through its professional laboratory-learning functionality."] },
  { title: "Changes to This Privacy Policy", paragraphs: ["This policy may be updated as AST Compass evolves. Material revisions will be reflected in the Last Updated date. Users are encouraged to review the policy periodically."] },
  { title: "Contact", paragraphs: ["Privacy questions may be submitted through the AST Compass Feedback page. No unmonitored privacy email address is published."] },
];

const termsSections: LegalSection[] = [
  { title: "1. Acceptance of Terms", paragraphs: ["These Terms govern access to and use of AST Compass, including its website, educational tools, learning modules, AST resources, resistance content, BCID Resistance Forecast, Concordance tools, image features, accounts, and related services. By using AST Compass, users agree to these Terms. Users who do not agree should not use it."] },
  { title: "2. About AST Compass", paragraphs: ["AST Compass is an independent educational and laboratory reference-support platform for exploring AST, resistance mechanisms, molecular markers, expected phenotypes, breakpoint concepts, concordance, rapid diagnostics, and clinical microbiology topics. Its principle is: A compass, not an autopilot."] },
  { title: "3. Educational Use Only", paragraphs: ["AST Compass is for education, training, learning, and laboratory reference support. It does not independently provide diagnosis, patient-specific advice or therapy recommendations, prescribing decisions, authorization of laboratory results or reports, or replacement for professional judgment. It is not represented as an FDA-cleared or FDA-approved medical device."] },
  { title: "4. Professional and Laboratory Responsibility", paragraphs: ["Users must independently verify information. Final testing, interpretation, reporting, and clinical decisions must follow validated procedures, institutional policy, manufacturer instructions, current authoritative standards, regulatory and quality-control requirements, and professional judgment. AST Compass must not be the sole authority for a patient result."] },
  { title: "5. Scientific Information Changes Over Time", paragraphs: ["Breakpoints, criteria, organism classifications, antimicrobial recommendations, resistance knowledge, platforms, and guidance evolve. AST Compass aims to identify sources, versions, review status, and dates where appropriate; users remain responsible for checking the current authoritative source."] },
  { title: "6. Scientific Content Status", bullets: ["DEMO: educational, developmental, example, or otherwise unvalidated content; not authoritative clinical criteria.", "REVIEWED: content checked against identified sources under the AST Compass review process.", "VERIFIED: content given an additional independent review under the AST Compass verification process."], paragraphs: ["These labels do not remove the user's responsibility to follow validated procedures and current standards. REVIEWED or VERIFIED must not be displayed unless the review actually occurred."] },
  { title: "7. Breakpoint Explorer", paragraphs: ["Breakpoint records may differ in review status. DEMO or Educational / Demo Data must not be treated as authoritative clinical breakpoints. Consult the current standard, manufacturer requirements, institutional procedures, and validated laboratory system before patient testing or reporting."] },
  { title: "8. BCID Resistance Forecast", paragraphs: ["BCID forecasts are pre-AST educational expectations connecting detected organisms and AMR markers with mechanisms and anticipated phenotypes. A marker does not predict the complete susceptibility profile; a negative result does not establish susceptibility; and multiplex attribution may be uncertain. Confirm with phenotypic AST where indicated. The forecast does not provide patient-specific treatment recommendations."] },
  { title: "9. Gene–Phenotype Concordance", paragraphs: ["Concordant, potentially concordant, discordant, cannot infer, not relevant, and further-investigation classifications are educational. They do not independently validate or invalidate a laboratory result. Investigate unexpected findings under validated procedures, quality systems, manufacturer guidance, and applicable standards."] },
  { title: "10. Image Concordance Analyzer", paragraphs: ["Automated image extraction may misread antimicrobial names, decimal points, MIC operators, categories, or other details. Users must review and confirm extracted information before analysis. Image analysis does not independently validate the original result."] },
  { title: "11. No PHI — De-Identified Material Only", paragraphs: ["DO NOT UPLOAD PHI OR PATIENT-IDENTIFIABLE INFORMATION. Remove names, record numbers, birth dates, addresses, contact details, account numbers, patient-linked accession or specimen identifiers, identifying barcodes or QR codes, photographs, and other identifiers.", "Screening may block suspected identifiers but cannot guarantee detection. Users remain responsible for appropriate de-identification."] },
  { title: "12. AST Compass Is Not a PHI Repository", paragraphs: ["AST Compass follows a No-PHI policy and is not an EMR, LIS, patient-record repository, clinical archive, or storage system for identifiable reports. It should not be considered HIPAA compliant for PHI unless explicitly stated after full review."] },
  { title: "13. Public Access", paragraphs: ["AST Compass currently provides its scientific and educational tools without requiring an account. Session activity may not survive browser, device, or storage changes, and recovery of unsaved activity is not guaranteed."] },
  { title: "14. Potential Future User Accounts", paragraphs: ["Optional account functionality may be enabled in the future after validation. It may provide saved analyses, saved de-identified images, BCID and Concordance history, learning progress, cross-device continuity, and other personalization. Applicable account terms and controls will be presented when that functionality becomes publicly available."] },
  { title: "15. Account Conduct", paragraphs: ["Users must provide accurate information and may not impersonate others, create fraudulent accounts, access another account, share credentials insecurely, circumvent security controls, or knowingly provide false account information. Abusive, fraudulent, unlawful, or security-threatening accounts may be restricted, suspended, or terminated."] },
  { title: "16. Third-Party Authentication", paragraphs: ["Third-party authentication, if offered, is also governed by the provider's terms and privacy policy. AST Compass is not responsible for the provider's independent operation, availability, or security practices."] },
  { title: "17. Saved Images and Analyses", paragraphs: ["Save only de-identified material you are authorized to use and that meets privacy, confidentiality, intellectual-property, and institutional requirements. Options may include saving image and analysis, analysis only, or neither. Content may be removed for privacy, security, compliance, maintenance, or enforcement."] },
  { title: "18. Acceptable Use", bullets: ["Do not upload PHI, malicious code, or harmful files; bypass screening; attack, scan, overload, or interfere with the platform; or access another user's data.", "Do not create fraudulent reports, misrepresent output as authorized clinical interpretation or treatment approval, impersonate others, violate intellectual-property rights, or use AST Compass unlawfully."] },
  { title: "19. Learning, AST Detective, and Competency Activities", paragraphs: ["Learning modules, cases, quizzes, knowledge checks, practice activities, progress, scores, or badges are educational. They are not certification, licensure, employer competency verification, CE credit, board certification, credentialing, or authorization unless explicitly stated under a separately governed validated program."] },
  { title: "20. Feedback", paragraphs: ["Feedback is voluntary. Do not include PHI. Submission does not authorize public identification or testimonial use. Non-confidential feedback may be used to improve content, functionality, usability, and development."] },
  { title: "21. Intellectual Property", paragraphs: ["AST Compass software, branding, logo, interface, educational structure, explanations, learning materials, graphics, case structures, and other original content may be protected by law. Use does not transfer ownership or permit false claims of authorship, affiliation, or endorsement."] },
  { title: "22. Third-Party Standards, Publications, and Materials", paragraphs: ["Third-party standards, publications, trademarks, manufacturer materials, and other resources remain their owners' property. Users must meet licensing and access requirements and consult original authoritative sources when necessary."] },
  { title: "23. Independence and No Endorsement", paragraphs: ["AST Compass is independent. References to CLSI, EUCAST, FDA, bioMérieux, Q-linea, and other organizations or products are for educational, identification, scientific, or sourcing purposes and do not imply affiliation, sponsorship, approval, or endorsement."] },
  { title: "24. External Links", paragraphs: ["External sites are independently operated. AST Compass does not control or accept responsibility for their availability, accuracy, security, privacy, terms, accessibility, or content. Review their policies."] },
  { title: "25. Platform Availability", paragraphs: ["AST Compass may be updated, modified, corrected, unavailable, restricted for maintenance, or discontinued. Continuous, uninterrupted, or error-free availability is not guaranteed."] },
  { title: "26. Accuracy, Errors, and Scientific Updates", paragraphs: ["The platform may contain errors, outdated or incomplete information, defects, extraction mistakes, data-entry errors, differences among standards or versions, and context-dependent interpretations. Verify important information and report suspected errors through Feedback."] },
  { title: "27. No Guarantee of Clinical Suitability", paragraphs: ["AST Compass is not guaranteed suitable for a particular workflow, population, institution, instrument, AST or molecular platform, jurisdiction, policy, or patient-care decision. Each laboratory must validate its own procedures."] },
  { title: "28. Disclaimer of Warranties", paragraphs: ["AST Compass is provided for educational and laboratory reference support on an “as available” basis. It does not guarantee complete or error-free science, uninterrupted software, universal breakpoint suitability, perfect extraction or PHI screening, perfect marker–phenotype prediction or attribution, durable links, or suitability for every user."] },
  { title: "29. Limitation of Liability", paragraphs: ["To the extent permitted by law, AST Compass and its creator should not be responsible for losses caused by inappropriate reliance on educational content when required verification was not performed. Nothing here excludes rights or duties that cannot legally be excluded. This provision should not be expanded without legal review."] },
  { title: "30. Security", paragraphs: ["Reasonable safeguards may protect accounts, authentication, saved analyses, de-identified images, private information, and infrastructure. Users must not bypass security. No internet platform guarantees absolute security; submit only information AST Compass requires.", "AST Compass may collect minimized, de-identified or non-sensitive technical telemetry to maintain reliability, detect errors, and improve platform functionality, subject to the Privacy Policy. This telemetry must not intentionally include PHI, private AST content, passwords, authentication tokens, or feedback text."] },
  { title: "31. Suspension or Termination", paragraphs: ["Access may be restricted, suspended, or terminated for security threats, abuse, unlawful activity, repeated No-PHI violations, unauthorized access attempts, malicious uploads, attacks, fraud, interference, or material Terms violations. Immediate action may be taken to protect users or the platform."] },
  { title: "32. Account Deletion", paragraphs: ["Account deletion should remove or schedule deletion of saved analyses, BCID sessions, Concordance history, learning progress, image metadata, and saved de-identified images, subject to technical, security, backup, fraud-prevention, or legal retention requirements."] },
  { title: "33. Changes to AST Compass", paragraphs: ["Features and scientific modules may be added, changed, or removed. A new feature is not automatically clinically validated. Applicable scientific content-status labels should continue to communicate review level."] },
  { title: "34. Changes to These Terms", paragraphs: ["Terms may be revised periodically. Material revisions will update the Last Updated date and may receive additional notice. Continued use after revised Terms take effect constitutes acceptance to the extent permitted by law."] },
  { title: "35. Governing Law and Jurisdiction", paragraphs: ["Governing-law and jurisdiction provisions will be established based on the legal structure and operating jurisdiction of AST Compass. Nothing in this section should be interpreted as selecting a jurisdiction that has not been formally designated. This section should be revisited after the legal structure is established or appropriate legal review occurs."] },
  { title: "36. Contact", paragraphs: ["Questions about these Terms may be submitted through the AST Compass Feedback page. A legal or support email may be added only when it exists and is actively monitored."] },
];

export function PrivacyPolicy({ onFeedback }: { onFeedback: () => void }) { return <LegalLayout kind="privacy" title="Privacy Policy" intro="What information AST Compass handles, why it is used, and the choices available to users." sections={privacySections} plainTitle="Privacy in Plain Language" plainItems={["AST Compass currently works without an account.", "Do not upload PHI or patient-identifiable information.", "AST images must be de-identified before upload.", "Automated PHI screening adds protection but cannot guarantee detection of every identifier.", "Public image analysis is session-only and is not added to persistent personal history.", "Account functionality may be enabled in the future after validation.", "AST Compass is educational—not a patient-record system."]} onFeedback={onFeedback}/>; }

export function TermsOfUse({ onFeedback }: { onFeedback: () => void }) { return <LegalLayout kind="terms" title="Terms of Use" intro="What AST Compass is for, its scientific boundaries, and user responsibilities." sections={termsSections} plainTitle="Terms in Plain Language" plainItems={["AST Compass is for education and laboratory reference support.", "It is not an autopilot for patient care.", "Verify important information against current authoritative standards and validated procedures.", "BCID molecular markers do not replace phenotypic AST.", "Do not upload PHI.", "Review image-extracted MICs and categories before analysis.", "All public tools currently work without an account; optional accounts may be enabled in the future.", "Educational scores are not professional certification unless explicitly stated.", "Third-party materials remain their owners' property.", "If something looks wrong, verify it and tell us through Feedback."]} onFeedback={onFeedback}/>; }
