import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import ts from "typescript";

const source=await readFile(new URL("../src/features/phenotypeMechanismEngine.ts",import.meta.url),"utf8");
const catalog=`const antibiotics=${JSON.stringify([
  ["ceftriaxone","Ceftriaxone","Third-generation cephalosporin"],["ceftazidime","Ceftazidime","Antipseudomonal cephalosporin"],["cefepime","Cefepime","Fourth-generation cephalosporin"],["cefoxitin","Cefoxitin screen","Cephamycin"],["ertapenem","Ertapenem","Carbapenem"],["meropenem","Meropenem","Carbapenem"],["imipenem","Imipenem","Carbapenem"],["aztreonam","Aztreonam","Monobactam"],["oxacillin","Oxacillin","Antistaphylococcal penicillin"],["vancomycin","Vancomycin","Glycopeptide"],["teicoplanin","Teicoplanin","Glycopeptide"],["ciprofloxacin","Ciprofloxacin","Fluoroquinolone"],["levofloxacin","Levofloxacin","Fluoroquinolone"]
].map(([id,name,className])=>({id,name,className})))};const mechanisms=${JSON.stringify([
  ["esbl","Extended-spectrum beta-lactamase"],["ampc","AmpC beta-lactamase"],["serine_carb","Carbapenemase phenotype"],["mbl","Metallo-beta-lactamase"],["pbp2a","Altered PBP2a/PBP2c"],["van_target","Vancomycin target alteration"],["mlsb","MLSB target methylation"],["quinolone","Fluoroquinolone target/protection"]
].map(([id,name])=>({id,name})))};const organisms=${JSON.stringify(["enterobacterales","ecoli","kpneumo","ecloacae","eaerogenes","cfreundii","smarcescens","morganella","providencia","pseudomonas","acinetobacter","staph_aureus","cons","slugdunensis","efaecalis","efaecium","spneumo","bhs","vgs"].map(id=>({id,gram:id.includes("staph")||id.startsWith("e")?"positive":"negative",group:""})))};const intrinsicPatterns=${JSON.stringify([{organismId:"kpneumo",antibioticId:"ampicillin",expectation:"Expected resistant",rationale:"Intrinsic ampicillin resistance"}])};`;
const compiled=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText.replace(/^import .*?;\s*/m,catalog);
const engine=await import(`data:text/javascript;base64,${Buffer.from(compiled).toString("base64")}`);
const row=(antimicrobialId,category)=>({id:crypto.randomUUID(),antimicrobialId,measurement:"",category});

test("E. coli expanded-spectrum cephalosporin resistance with retained carbapenems is ESBL compatible",()=>{const result=engine.analyzePhenotype("ecoli",[row("ceftriaxone","R"),row("ceftazidime","R"),row("meropenem","S")]);assert.equal(result.candidates[0].mechanismId,"esbl");assert.match(result.candidates[0].compatibility,/Highly compatible|Compatible/);});
test("Enterobacter cloacae complex AmpC-like profile considers AmpC",()=>{const result=engine.analyzePhenotype("ecloacae",[row("cefoxitin","R"),row("ceftriaxone","R"),row("meropenem","S")]);assert.ok(result.candidates.some(c=>c.mechanismId==="ampc"));});
test("K. pneumoniae broad beta-lactam and carbapenem resistance considers a carbapenemase phenotype",()=>{const result=engine.analyzePhenotype("kpneumo",[row("meropenem","R"),row("imipenem","R"),row("cefepime","R")]);assert.ok(result.candidates.some(c=>c.mechanismId==="serine_carb"));});
test("P. aeruginosa single-drug resistance does not force a specific mechanism",()=>{const result=engine.analyzePhenotype("pseudomonas",[row("ciprofloxacin","R")]);assert.equal(result.insufficient,true);});
test("S. aureus MRSA-like profile suggests altered PBP context without detection language",()=>{const result=engine.analyzePhenotype("staph_aureus",[row("oxacillin","R")]);assert.equal(result.candidates[0].mechanismId,"pbp2a");assert.doesNotMatch(JSON.stringify(result),/detected|positive for|gene present/i);});
test("E. faecium VRE-like profile suggests acquired glycopeptide resistance context",()=>{const result=engine.analyzePhenotype("efaecium",[row("vancomycin","R")]);assert.equal(result.candidates[0].mechanismId,"van_target");assert.deepEqual(result.candidates[0].candidateMarkers,["vanA","vanB"]);});
test("intrinsic findings are shown before acquired-mechanism inference",()=>{const result=engine.analyzePhenotype("kpneumo",[row("ampicillin","R")]);assert.equal(result.intrinsicFindings.length,1);assert.equal(result.insufficient,true);});
test("mixed and insufficient profiles remain conservative and multiple candidates are allowed",()=>{const sparse=engine.analyzePhenotype("ecoli",[row("ciprofloxacin","R")]);assert.equal(sparse.insufficient,true);const competing=engine.analyzePhenotype("ecloacae",[row("cefoxitin","R"),row("ceftriaxone","R"),row("ceftazidime","R"),row("meropenem","S")]);assert.ok(competing.candidates.length>=2);});
test("all rules are source-linked Draft content and UI preserves the molecular-inference boundary",async()=>{assert.ok(engine.phenotypeSignatures.every(s=>s.sourceIds.length&&s.reviewStatus==="Draft"));const ui=await readFile(new URL("../src/features/PhenotypeMechanismAnalyzer.tsx",import.meta.url),"utf8");assert.match(ui,/PHENOTYPE-BASED INFERENCE/);assert.match(ui,/Possible molecular marker/);assert.doesNotMatch(ui,/CTX-M detected|KPC present|NDM positive|Gene detected/);});
